### ISSUE TITLE
About AnimateGIF.

### ISSUE THREAD

**Issue by DaMoXin** [MickeyKnox/piv#1]
Can you write an example of using sfml library and stb_image.h to play animated gif(s)  in your 
repositories on github.Thank you.

**Comment by DaMoXin** [comment]
I think you should make your email public.

**Comment by cyberdynesoftware** [comment]
Which Email are you referring to?

There is a complete working [example](https://github.com/SFML/SFML/wiki/Source%3A-Animated-GIF) in the SFML Wiki.

**Comment by DaMoXin** [comment]
Thank you.I've used this example, but there are some problems when it runs on my device. I'm using gcc compiler, so I hope you can improve it so that it can be better used on other devices.

**Comment by DaMoXin** [comment]
For beginners like me, it's very difficult to write a GIF decoding program, and there are few references on the Internet, and there are very few things about sfml and animated GIF on GitHub.

**Comment by cyberdynesoftware** [comment]
You'd have to be a little bit more specific about the problems you're facing in order for me to help you. Besides the example in the SFML forum there is also the code in this repository, which builds on said code.
